org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# ВАЖНО: замени на свой реальный ключ и НЕ коммить его в общий репозиторий
# (в реальном проекте вынести эту строку в gradle.properties из .gitignore).
MAPTILER_API_KEY=YOUR_MAPTILER_API_KEY_HERE
